# **Penting**
- Jangan mengubah atau menambahkan cell text yang sudah disediakan, Anda hanya perlu mengerjakan cell code yang sudah disediakan.
- Pastikan seluruh kriteria memiliki output yang sesuai, karena jika tidak ada output dianggap tidak selesai.
- Misal, Anda menggunakan df = df.dropna() silakan gunakan df.isnull().sum() sebagai tanda sudah berhasil. Silakan sesuaikan seluruh output dengan perintah yang sudah disediakan.
- Pastikan Anda melakukan Run All sebelum mengirimkan submission untuk memastikan seluruh cell berjalan dengan baik.
- Pastikan Anda menggunakan variabel df dari awal sampai akhir dan tidak diperbolehkan mengganti nama variabel tersebut.
- Hapus simbol pagar (#) pada kode yang bertipe komentar jika Anda menerapkan kriteria tambahan
- Biarkan simbol pagar (#) jika Anda tidak menerapkan kriteria tambahan
- Pastikan Anda mengerjakan sesuai section yang sudah diberikan tanpa mengubah judul atau header yang disediakan.

# **1. Import Library**
Pada tahap ini, Anda perlu mengimpor beberapa pustaka (library) Python yang dibutuhkan untuk analisis data dan pembangunan model machine learning.

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report
import joblib
import warnings
warnings.filterwarnings('ignore')

# **2. Memuat Dataset dari Hasil Clustering**
Memuat dataset hasil clustering dari file CSV ke dalam variabel DataFrame.

In [2]:
# Gunakan dataset hasil clustering yang memiliki fitur Target
# Silakan gunakan dataset data_clustering jika tidak menerapkan Interpretasi Hasil Clustering [Advanced]
# Silakan gunakan dataset data_clustering_inverse jika menerapkan Interpretasi Hasil Clustering [Advanced]
# Lengkapi kode berikut
df = pd.read_csv('data_clustering.csv')

In [3]:
df.head()

TransactionAmount  PreviousTransactionDate  TransactionType  Location  \
0           0.007207                      680                1        36   
1           0.195940                     1178                1        15   
2           0.065680                     1262                1        23   
3           0.096016                      818                1        33   
4           0.047888                      635                1        28   

   Channel  CustomerAge  CustomerOccupation  TransactionDuration  \
0        0     0.838710                   0             0.244828   
1        0     0.806452                   0             0.451724   
2        2     0.016129                   3             0.158621   
3        2     0.129032                   3             0.051724   
4        0     0.000000                   3             0.558621   

   LoginAttempts  AccountBalance  TransactionDate  AmountBin  AgeBin  Target  
0            0.0        0.336832              105          1       1       3  
1            0.0        0.918055              192          2       1       3  
2            0.0        0.068637               41          1       2       2  
3            0.0        0.569198              163          1       2       3  
4            0.0        0.045738               13          1       2       3

# **3. Data Splitting**
Tahap Data Splitting bertujuan untuk memisahkan dataset menjadi dua bagian: data latih (training set) dan data uji (test set).

In [4]:
# Menggunakan train_test_split() untuk melakukan pembagian dataset.
X = df.drop('Target', axis=1)
y = df['Target']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# **4. Membangun Model Klasifikasi**
Setelah memilih algoritma klasifikasi yang sesuai, langkah selanjutnya adalah melatih model menggunakan data latih.

Berikut adalah rekomendasi tahapannya.
1. Menggunakan algoritma klasifikasi yaitu Decision Tree.
2. Latih model menggunakan data yang sudah dipisah.

In [5]:
from sklearn.tree import DecisionTreeClassifier

# Buatlah model klasifikasi menggunakan Decision Tree
dt_model = DecisionTreeClassifier(random_state=42)
dt_model.fit(X_train, y_train)
y_pred_dt = dt_model.predict(X_test)

In [6]:
# Menyimpan Model
import joblib
joblib.dump(dt_model, 'decision_tree_model.h5')

['decision_tree_model.h5']

# **5. Memenuhi Kriteria Skilled dan Advanced dalam Membangun Model Klasifikasi**



**Biarkan kosong jika tidak menerapkan kriteria skilled atau advanced**

In [7]:
# Melatih model menggunakan algoritma klasifikasi selain Decision Tree.

# Import library yang diperlukan
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix

# Inisialisasi dan latih model RandomForest
rf_model = RandomForestClassifier(random_state=42)
rf_model.fit(X_train, y_train)
y_pred_rf = rf_model.predict(X_test)

# Inisialisasi dan latih model LogisticRegression
lr_model = LogisticRegression(max_iter=200)
lr_model.fit(X_train, y_train)
y_pred_lr = lr_model.predict(X_test)

# Evaluasi model RandomForest
print("Random Forest Classifier:")
print(confusion_matrix(y_test, y_pred_rf))
print(classification_report(y_test, y_pred_rf))

# Evaluasi model LogisticRegression
print("Logistic Regression:")
print(confusion_matrix(y_test, y_pred_lr))
print(classification_report(y_test, y_pred_lr))

Random Forest Classifier:
[[107   0   0   0]
 [  0  95   0   0]
 [  0   0 113   0]
 [  0   0   0 122]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       107
           1       1.00      1.00      1.00        95
           2       1.00      1.00      1.00       113
           3       1.00      1.00      1.00       122

    accuracy                           1.00       437
   macro avg       1.00      1.00      1.00       437
weighted avg       1.00      1.00      1.00       437

Logistic Regression:
[[86  0  0 21]
 [ 0 82 13  0]
 [ 0 47 43 23]
 [ 8  6 31 77]]
              precision    recall  f1-score   support

           0       0.91      0.80      0.86       107
           1       0.61      0.86      0.71        95
           2       0.49      0.38      0.43       113
           3       0.64      0.63      0.63       122

    accuracy                           0.66       437
   macro avg       0.66      0.67      0.66       437


In [8]:
# Menampilkan hasil evaluasi akurasi, presisi, recall, dan F1-Score pada seluruh algoritma yang sudah dibuat.

print('Decision Tree:')
print(classification_report(y_test, y_pred_dt))
print('Random Forest:')
print(classification_report(y_test, y_pred_rf))
print('Logistic Regression:')
print(classification_report(y_test, y_pred_lr))

Decision Tree:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       107
           1       1.00      1.00      1.00        95
           2       1.00      1.00      1.00       113
           3       1.00      1.00      1.00       122

    accuracy                           1.00       437
   macro avg       1.00      1.00      1.00       437
weighted avg       1.00      1.00      1.00       437

Random Forest:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       107
           1       1.00      1.00      1.00        95
           2       1.00      1.00      1.00       113
           3       1.00      1.00      1.00       122

    accuracy                           1.00       437
   macro avg       1.00      1.00      1.00       437
weighted avg       1.00      1.00      1.00       437

Logistic Regression:
              precision    recall  f1-score   support

           0       0.91 

In [9]:
# Menyimpan Model Selain Decision Tree
# Model ini bisa lebih dari satu
import joblib
joblib.dump(rf_model, 'explore_RandomForest_classification.h5')
joblib.dump(lr_model, 'explore_LogisticRegression_classification.h5')

['explore_LogisticRegression_classification.h5']

Hyperparameter Tuning Model

Pilih salah satu algoritma yang ingin Anda tuning

In [10]:
# Lakukan Hyperparameter Tuning dan Latih ulang.
# Lakukan dalam satu cell ini saja.

param_grid = {
    'n_estimators': [50, 100, 150],
    'max_depth': [None, 5, 10],
    'min_samples_split': [2, 5, 10]
}
gs = GridSearchCV(RandomForestClassifier(random_state=42), param_grid, cv=3, scoring='f1_macro')
gs.fit(X_train, y_train)
y_pred_gs = gs.predict(X_test)

In [11]:
# Menampilkan hasil evaluasi akurasi, presisi, recall, dan F1-Score pada algoritma yang sudah dituning.
print('Random Forest Tuned:')
print(classification_report(y_test, y_pred_gs))

Random Forest Tuned:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       107
           1       1.00      1.00      1.00        95
           2       1.00      1.00      1.00       113
           3       1.00      1.00      1.00       122

    accuracy                           1.00       437
   macro avg       1.00      1.00      1.00       437
weighted avg       1.00      1.00      1.00       437



In [12]:
# Menyimpan Model hasil tuning
import joblib
joblib.dump(gs.best_estimator_, 'tuning_classification.h5')

['tuning_classification.h5']

End of Code